package com.hs.eai.monitor.order.model;

// Generated 22-aug-2012 9:41:49 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OrderHdr generated by hbm2java
 */
public class OrderHdr implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4746117933640417721L;
	private Integer id;
	private OrderStatus orderStatus;
	private Integer companyCodeId;
	private String refno;
	private Integer shipto;
	private Integer billto;
	private Integer countryId;
	private Integer systemSourceId;
	private Integer systemDestinationId;
	private Date orderDate;
	private Date dataSent;
	private java.lang.Boolean orderConfirmation;
	private java.lang.Boolean shipmentConfirmation;
	private String emailAddress;
	private Integer salesOrganizationId;
	private String name;
	private Date dateCreated;
	private Date dateUpdated;
	private Set<OrderDetail> orderDetails = new HashSet<OrderDetail>(0);
	private String userId;
	private String ogonePaymentId;
	private String orderEmailConf;
	private String shipEmailConf;
	private String orderComment;
	private String customerOrderReference;
	private String shippingMethod;
	private String paymentMethod;
	private String promoCode;
	
	public OrderHdr() {
	}

	public OrderHdr(Integer id, OrderStatus orderStatus, Date orderRecieved, java.lang.Boolean orderConfirmation, java.lang.Boolean shipmentConfirmation) {
		this.id = id;
		this.orderStatus = orderStatus;
		this.dataSent = orderRecieved;
		this.orderConfirmation = orderConfirmation;
		this.shipmentConfirmation = shipmentConfirmation;
	}

	public OrderHdr(Integer id, OrderStatus orderStatus, Integer companyCode, String refno, Integer shipto, Integer billto, Date orderDate, Date orderRecieved, java.lang.Boolean orderConfirmation, java.lang.Boolean shipmentConfirmation, String emailAddress, Set<OrderDetail> orderDetails, String ogonePaymentId, String orderEmailConf, String shipEmailConf, String orderComment, String customerOrderReference, String shippingMethod, String paymentMethod, String promoCode) {
		this.id = id;
		this.orderStatus = orderStatus;
		this.companyCodeId = companyCode;
		this.refno = refno;
		this.shipto = shipto;
		this.billto = billto;
		this.orderDate = orderDate;
		this.dataSent = orderRecieved;
		this.orderConfirmation = orderConfirmation;
		this.shipmentConfirmation = shipmentConfirmation;
		this.emailAddress = emailAddress;
		this.orderDetails = orderDetails;
		this.ogonePaymentId = ogonePaymentId;
		this.orderEmailConf = orderEmailConf;
		this.shipEmailConf = shipEmailConf;
		this.orderComment = orderComment;
		this.customerOrderReference = customerOrderReference;
		this.shippingMethod = shippingMethod;
		this.paymentMethod = paymentMethod;
		this.promoCode = promoCode;
	}

	public String getPaymentMethod() {
		return paymentMethod;
	}

	public void setPaymentMethod(String shippingMethod) {
		this.paymentMethod = shippingMethod;
	}

	public String getShippingMethod() {
		return shippingMethod;
	}

	public void setShippingMethod(String shippingMethod) {
		this.shippingMethod = shippingMethod;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public OrderStatus getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(OrderStatus orderStatus) {
		this.orderStatus = orderStatus;
	}

	public Integer getCompanyCodeId() {
		return this.companyCodeId;
	}

	public void setCompanyCodeId(Integer companyCodeId) {
		this.companyCodeId = companyCodeId;
	}

	public String getRefno() {
		return this.refno;
	}

	public void setRefno(String refno) {
		this.refno = refno;
	}

	public Integer getShipto() {
		return this.shipto;
	}

	public void setShipto(Integer shipto) {
		this.shipto = shipto;
	}

	public Integer getBillto() {
		return this.billto;
	}

	public void setBillto(Integer billto) {
		this.billto = billto;
	}

	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}
	
	public Date getDataSent() {
		return dataSent;
	}

	public void setDataSent(Date dataSent) {
		this.dataSent = dataSent;
	}

	public java.lang.Boolean getOrderConfirmation() {
		return this.orderConfirmation;
	}

	public void setOrderConfirmation(java.lang.Boolean orderConfirmation) {
		this.orderConfirmation = orderConfirmation;
	}

	public java.lang.Boolean getShipmentConfirmation() {
		return this.shipmentConfirmation;
	}

	public void setShipmentConfirmation(java.lang.Boolean shipmentConfirmation) {
		this.shipmentConfirmation = shipmentConfirmation;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public Set<OrderDetail> getOrderDetails() {
		return this.orderDetails;
	}

	public void setOrderDetails(Set<OrderDetail> orderDetails) {
		this.orderDetails = orderDetails;
	}

	public Date getDateCreated() {
		return dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public Date getDateUpdated() {
		return dateUpdated;
	}

	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

	public Integer getCountryId() {
		return countryId;
	}

	public void setCountryId(Integer countryId) {
		this.countryId = countryId;
	}

	public Integer getSystemSourceId() {
		return systemSourceId;
	}

	public void setSystemSourceId(Integer systemSourceId) {
		this.systemSourceId = systemSourceId;
	}

	public Integer getSystemDestinationId() {
		return systemDestinationId;
	}

	public void setSystemDestinationId(Integer systemDestinationId) {
		this.systemDestinationId = systemDestinationId;
	}

	public Integer getSalesOrganizationId() {
		return salesOrganizationId;
	}

	public void setSalesOrganizationId(Integer salesOrganizationId) {
		this.salesOrganizationId = salesOrganizationId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getOgonePaymentId() {
		return ogonePaymentId;
	}

	public void setOgonePaymentId(String paymentId) {
		this.ogonePaymentId = paymentId;
	}

	public String getOrderEmailConf() {
		return orderEmailConf;
	}

	public void setOrderEmailConf(String orderEmailConf) {
		this.orderEmailConf = orderEmailConf;
	}

	public String getShipEmailConf() {
		return shipEmailConf;
	}

	public void setShipEmailConf(String shipEmailConf) {
		this.shipEmailConf = shipEmailConf;
	}
	
	public String getOrderComment() {
		return this.orderComment;
	}

	public void setOrderComment(String orderComment) {
		this.orderComment = orderComment;
	}

	public String getCustomerOrderReference() {
		return customerOrderReference;
	}

	public void setCustomerOrderReference(String customerOrderReference) {
		this.customerOrderReference = customerOrderReference;
	}

	public String getPromoCode() {
		return promoCode;
	}

	public void setPromoCode(String promoCode) {
		this.promoCode = promoCode;
	}
}