package com.hs.eai.monitor.order.model;

// Generated 22-aug-2012 9:41:49 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * OrderStatus generated by hbm2java
 */
public class OrderStatus implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String code;
	private String description;
	private Set<OrderHdr> orderHdrs = new HashSet<OrderHdr>(0);

	public OrderStatus() {
	}

	public OrderStatus(Integer id, String code, String description) {
		this.id = id;
		this.code = code;
		this.description = description;
	}

	public OrderStatus(Integer id, String code, String description, Set<OrderHdr> orderHdrs) {
		this.id = id;
		this.code = code;
		this.description = description;
		this.orderHdrs = orderHdrs;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<OrderHdr> getOrderHdrs() {
		return this.orderHdrs;
	}

	public void setOrderHdrs(Set<OrderHdr> orderHdrs) {
		this.orderHdrs = orderHdrs;
	}

}
